name: user
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  multi_image_picker: ^4.7.14
  #image_picker: ^0.6.7+6
  flutter_rounded_date_picker: 2.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^2.3.1
  pageview_indicator_plugins: ^0.0.2
  scoped_model: ^1.0.1
  dio: ^3.0.10
  time_picker_widget: ^1.0.0+10
  shared_preferences: ^2.0.5
  connectivity: ^3.0.6
  path_provider: ^2.0.1
  flutter_inappwebview: ^5.3.2
  intl: ^0.17.0
  #advance_pdf_viewer: ^1.2.2
  #advance_pdf_viewer: ^1.2.0
  #path_provider: ^1.6.8
  #flushbar: ^1.10.0
  another_flushbar: ^1.10.23
  dropdown_search: ^0.6.3
  #dropdown_search: ^0.4.4
  rflutter_alert: ^1.1.0
  file_picker:
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  #cupertino_icons: ^0.1.2
  #image_cropper: ^1.3.1
  # image_picker: ^0.6.5+2
  #image_crop: ^0.4.0
  #image_cropper: ^1.4.0
  #image_cropper: ^0.0.9
  #image_picker: ^0.6.7+6

  #image_cropper: ^1.3.0
  date_format: ^2.0.2
  convex_bottom_bar: ^2.7.1
  percent_indicator: "^2.1.7+2"
#  syncfusion_flutter_calendar: ^19.1.67
  otp_text_field: ^1.1.1
  flutter_toggle_tab: ^1.1.4
  url_launcher: ^6.0.6
  intro_slider: ^3.0.2
  package_info: ^2.0.2
  flutter_webview_plugin: ^0.4.0
  # flutter_login_facebook: ^0.5.0
  #webview_flutter: ^2.0.12
  lottie: ^1.1.0
  date_picker_timeline: ^1.2.3
  flutter_rating_bar: ^4.0.0
  flutter_share: ^2.0.0
  #fl_chart: ^0.40.2
  pie_chart: ^5.1.0
  #fl_chart: ^0.40.0
  #image_picker: ^0.8.3
  geolocator: '^5.1.1'
  geocoder: ^0.2.1
  webview_flutter: ^2.0.13
  #video_player: ^2.1.13
  #table_calendar: ^3.0.2
  multi_select_item: ^1.0.3
#  crypto: ^3.0.1
  firebase_messaging: ^10.0.1

  flutter_local_notifications: ^6.0.0
#  flutter_local_notifications: ^9.2.0
  firebase_core: ^1.2.1
  flutter_typeahead: ^3.2.0
  share: ^2.0.4
  custom_rating_bar: ^1.0.2
  flutter_sms: ^2.3.2
  flutter_pdfview: ^1.2.1
  calendar_timeline: ^1.0.4
#  add_2_calendar: ^2.1.2
  unicorndial: ^1.1.5
#  device_calendar: ^3.1.0
  video_player: ^2.1.5
  chewie: ^1.2.2
#  device_calendar: ^3.1.0
#  agora_rtc_engine: ^3
#  agora_rtc_engine: ^4.0.7
  permission_handler: ^8.1.4
  device_info_plus: ^3.0.1
#  android_multiple_identifier: ^1.0.3
  unique_identifier: ^0.2.2
#  audioplayers: ^0.19.0
#  flutter_sound_lite: ^8.3.12
#  audioplayers: ^0.18.2
  showcaseview: ^1.1.4
  flutter_phone_direct_caller: ^2.1.0
  flutter_contacts: ^1.1.1
  sms_autofill: ^2.2.0
#font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/intro/
    - assets/audio/
    - assets/health_tips/
    - assets/icon/ipsita/
    - assets/icon/mobile_icon/
    - assets/New folder/
    - assets/icon/
    - assets/images/premium.png
    - assets/intro/srilankaPM.jpg






  fonts:

    - family:  Monte
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family:  MonteMed
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family:  DINLight
      fonts:
        - asset: fonts/DINNextLTPro-Light.otf

    - family:  DINBold
      fonts:
        - asset: fonts/DINNextLTPro-Bold.otf

    - family:  DINMed
      fonts:
        - asset: fonts/DINNextLTPro-Medium.otf

    - family:  DINReg
      fonts:
        - asset: fonts/DINNextLTPro-Regular.otf

